{
 "title": "SessionAI",
 "description": "SessionAI assignment",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Alert-system-error",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"} |= `level=error` [$__auto])"
    }
   ]
  },
  {
   "title": "system-warning",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"} |= `level=warn` [$__auto])"
    }
   ]
  },
  {
   "title": "okhamkar-syslog-error-",
   "type": "logs",
   "description": "Error capturing from Ojas Khamkar's local laptop in /var/logs/",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"} | logfmt"
    }
   ]
  },
  {
   "title": "okhamkar-grafana-error-logstream",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/grafana/grafana.log\"} | logfmt"
    }
   ]
  }
 ]
}